theme: jekyll-theme-midnight
title: Issaih Perez's ePortofolio Page!

# toc: true   Uncomment if you want Table of Contents Enabled   

url: "https://github.com/IssaihPerez/Capstone-2025"

exclude:
  - README.md